---
abstract: 'Simple, flexible system to implement workflows'
author:
  - 'Jonas B. NIelsen <jonasbn@cpan.org>'
build_requires:
  DBD::Mock: 0.1
  List::MoreUtils: 0
  Test::Exception: 0
  Test::More: 0.41
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Workflow
no_index:
  directory:
    - eg
    - t
provides:
  Workflow:
    file: lib/Workflow.pm
    version: 1.34_1
  Workflow::Action:
    file: lib/Workflow/Action.pm
    version: 1.10
  Workflow::Action::InputField:
    file: lib/Workflow/Action/InputField.pm
    version: 1.09
  Workflow::Action::Mailer:
    file: lib/Workflow/Action/Mailer.pm
    version: 1.01
  Workflow::Action::Null:
    file: lib/Workflow/Action/Null.pm
    version: 1.03
  Workflow::Base:
    file: lib/Workflow/Base.pm
    version: 1.08
  Workflow::Condition:
    file: lib/Workflow/Condition.pm
    version: 1.07
  Workflow::Condition::Evaluate:
    file: lib/Workflow/Condition/Evaluate.pm
    version: 1.02
  Workflow::Condition::HasUser:
    file: lib/Workflow/Condition/HasUser.pm
    version: 1.05
  Workflow::Config:
    file: lib/Workflow/Config.pm
    version: 1.13
  Workflow::Config::Perl:
    file: lib/Workflow/Config/Perl.pm
    version: 1.03
  Workflow::Config::XML:
    file: lib/Workflow/Config/XML.pm
    version: 1.05
  Workflow::Context:
    file: lib/Workflow/Context.pm
    version: 1.05
  Workflow::Exception:
    file: lib/Workflow/Exception.pm
    version: 1.09
  Workflow::Factory:
    file: lib/Workflow/Factory.pm
    version: 1.20
  Workflow::History:
    file: lib/Workflow/History.pm
    version: 1.10
  Workflow::Persister:
    file: lib/Workflow/Persister.pm
    version: 1.10
  Workflow::Persister::DBI:
    file: lib/Workflow/Persister/DBI.pm
    version: 1.19
  Workflow::Persister::DBI::AutoGeneratedId:
    file: lib/Workflow/Persister/DBI/AutoGeneratedId.pm
    version: 1.06
  Workflow::Persister::DBI::ExtraData:
    file: lib/Workflow/Persister/DBI/ExtraData.pm
    version: 1.05
  Workflow::Persister::DBI::SequenceId:
    file: lib/Workflow/Persister/DBI/SequenceId.pm
    version: 1.05
  Workflow::Persister::File:
    file: lib/Workflow/Persister/File.pm
    version: 1.11
  Workflow::Persister::RandomId:
    file: lib/Workflow/Persister/RandomId.pm
    version: 1.03
  Workflow::Persister::SPOPS:
    file: lib/Workflow/Persister/SPOPS.pm
    version: 1.07
  Workflow::Persister::UUID:
    file: lib/Workflow/Persister/UUID.pm
    version: 1.03
  Workflow::State:
    file: lib/Workflow/State.pm
    version: 1.15
  Workflow::Validator:
    file: lib/Workflow/Validator.pm
    version: 1.05
  Workflow::Validator::HasRequiredField:
    file: lib/Workflow/Validator/HasRequiredField.pm
    version: 1.05
  Workflow::Validator::InEnumeratedType:
    file: lib/Workflow/Validator/InEnumeratedType.pm
    version: 1.04
  Workflow::Validator::MatchesDateFormat:
    file: lib/Workflow/Validator/MatchesDateFormat.pm
    version: 1.06
requires:
  Carp: 0
  Class::Accessor: 0.18
  Class::Factory: 1
  Class::Observable: 1.04
  DBI: 0
  Data::Dumper: 0
  DateTime: 0.15
  DateTime::Format::Strptime: 1
  Exception::Class: 1.1
  File::Slurp: 0
  Log::Dispatch: 2
  Log::Log4perl: 0.34
  Safe: 0
  XML::Simple: 2
resources:
  license: http://dev.perl.org/licenses/
version: 1.34_1
